# Generated by Django 2.2.1 on 2019-05-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190526_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_upload',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='contact_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=150),
        ),
    ]
