# Generated by Django 2.2.1 on 2019-05-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190527_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
